config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :playlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :playlist, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || playlists_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index
    @playlists = Playlist.where(user_id: current_user)
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user = current_user
    if @playlist.save
      redirect_to playlists_path
    else
      flash[:alert] = "Sorry the details for your playlist don't work, please try again"
      redirect_to playlists_path
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    redirect_to playlists_path
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easystreamin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Syne+Mono&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <meta name="description" content="Play all your favourite Spotify Playlists Online for free!">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="Easy Streamin'" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="eslaptop.png" />
    <meta property="og:description" content="Play all your favourite Spotify Playlists Online for free!" />
    <meta property="og:site_name" content="Easy Streamin'" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="Easy Streamin'">
    <meta name="twitter:title" content="Easy Streamin'">
    <meta name="twitter:description" content="Play all your favourite Spotify Playlists Online for free!">
    <meta name="twitter:image:src" content="eslaptop.png">
  </head>

  <body style="background-color: white;" >
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <div class="popup d-flex justify-content-center" id="popup">
      <div class="bg-danger w-50 text-center text-white p-3">
        <h5 class="p-2">You are on a mobile device</h5>
        <p>Unfortunately this app is for desktop only</p>
        <a onclick="closePopup()" class="bg-success px-2 py-1" style="border: 2px solid white; border-radius: 4px;">
          <span style="color:black;">Got it!</span>
        </a>
      </div>
    </div>
  <div>
  <div class="bg-linear text-white" id="bg-popup">
    <div class="text-center px-2 py-5">
      <h2>Play all your favourite Spotify Playlists Online for free!</h2>
    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12 border-right pb-4">
        <div class="text-center py-5">
          <%= image_tag("spotifylaptop.png", :alt => "Spotify on Desktop", width: "200px")%>
        </div>
        <div class="container">
          <h4 class="p-4">
            <span style="border-bottom: 4px white solid;">On Spotify Desktop</span>*:
          </h4>
          <ul class="py-3 play-list">
            <li>Make your playlist on your Spotify Free account</li>
            <li>Click
              &nbsp; <code><i class="fas fa-ellipsis-h"></i> (More) </code>
              <i class="fas fa-arrow-circle-right"></i><code> Share </code>
              <i class="fas fa-arrow-circle-right"></i><code> Copy Embed Code</code>
            </li>
          </ul>
          <p class="p-3" style="font-size: 0.6em;">
            <em>*Please note that sadly the Spotify App on your Mobile, Tablet or Chromebook device will not support these features</em>
          </p>
        </div>
      </div>
      <div class="col-md-6 col-sm-12 border-left pb-4">
        <div class="text-center py-5">
          <%= image_tag("eslaptop.png", :alt => "Spotify on Desktop", width: "200px") %>
        </div>
        <div class="container">
          <h4 class="p-4">
            <span style="border-bottom: 4px white solid;">On easy streamin</span>':
          </h4>
          <ul class="py-3 play-list">
            <li>Create a free account</li>
            <li style="line-height: 2em">Click on
              <span style="padding: 4px 8px; color: black; border: 2px solid white; border-radius: 4px; margin: 8px;" class="bg-success">
                Add Playlist
              </span>
            </li>
            <li>Choose a name for your playlist and copy in the code from Spotify</li>
            <li>🎉 Et Voila!</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<%= javascript_tag do -%>
  window.onload = function activatePopup() {
    if (screen.width < 700 ) {
      document.getElementById("bg-popup").classList.add("bg-popup");
      document.getElementById("popup").style.visibility = "visible";
    }
  }
  function closePopup () {
    document.getElementById("bg-popup").classList.remove("bg-popup");
    document.getElementById("popup").style.visibility = "hidden";
  }
<% end -%>
</div>

app/views/playlists/index.html.erb
<div class="bg-linear text-center text-white">
  <h2 class="pt-5 pb-3">My Playlists</h2>
  <% if @playlists.length < 1 %>
    <div class="container my-5 py-5" style="height: 100vh">
      <h2>¯\_(ツ)_/¯</h2>
      <h2>No playlists to show</h2>
      <ul class="list-unstyled m-5">
        <li>Click on 'Add Playlist' above</li>
        <li>Go to your Spotify Desktop and click
          &nbsp; <code><i class="fas fa-ellipsis-h"></i> (More) </code>
          <i class="fas fa-arrow-circle-right"></i><code> Share </code>
          <i class="fas fa-arrow-circle-right"></i><code> Copy Embed Code</code>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="row">
      <% @playlists.reverse.each do |playlist| %>
        <div style="padding: 8px 0; " class="col-lg-4 col-md-6 cold-sm-12">
          <div style="display: grid; grid-template-columns: 1fr 1fr 1fr">
            <div></div>
            <div>
              <h3>
                <%= playlist.name %>
              </h3>
            </div>
            <div>
              <%= link_to playlist_path(playlist), data: { confirm: "Delete #{playlist.name}?" }, method: :delete do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
          <%=playlist.url.html_safe%>
        </div>
      <% end %>
    </div>
     <footer style="background-color:black;color:white; padding: 8px;" class="container-fluid text-right">
      Questions? Please
      <a href="mailto:simonwaltondev@gmail.com?subject=Easy Streamin Enquiry" target="_blank">
        get in touch
      </a>
    </footer>
  <% end %>
</div>

app/views/playlists/new.html.erb
<div class="pt-4 text-white font-weight-bolder bg-danger" style="height: 90vh;">
  <div class="container">
  <%= simple_form_for [@playlist] do |f| %>
  <%= f.input :name, placeholder: "Name your playlist" %>
  <%= f.input :url, placeholder: "Paste here output from 'Copy Embed Code'. Eg. <iframe>..." %>
  <%= f.button :submit, class:"bg-success mb-3" %>
  <% end %>
  <%= link_to "Back", playlists_path %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="font-weight: 600;">
  <h2 style="font-size: 1.7em">
    <%= link_to root_path, class: "text-danger" do%>
      <div class="text-center">
        <%= image_tag("eslaptop.png", :alt => "Spotify on Desktop", width: "30px") %>
        easy streamin'
        </div>
    <% end %>
  </h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item mr-3 my-3">
          <%= link_to "Add Playlist", new_playlist_path, method: :get, class: "bg-success", style: "color: black; padding: 8px 12px; border: 2px solid white; border-radius: 4px;" %>
        </li>
        <li class="nav-item active m-3">
          <%= link_to "Playlists", "/playlists", class: "text-danger" %>
        </li>
        <li class="nav-item m-3">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-danger" %>
        </li>
      <% else %>
        <li class="nav-item m-3">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-danger" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>